# Homework 3

by Nick Rüdlinger


## Problem 1

given code

In [1]:
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

implementation using numpy, without a loop

In [20]:
import numpy as np

def func1_np(names, db):
    return np.arange(len(db))[np.isin(db, names)]

test its behaviour

In [28]:
# simple test
names = ["nick", "marc", "oli", "jana"]
db = ["nick", "jana", "peter", "oli"]

print(func1(names, db))
print(func1_np(names, db)) # returns numpy array instead of a list

[0, 3, 1]
[0 1 3]


In [48]:
# bigger test to see the time effect
import random
import string

random.seed(32)

letters = string.ascii_lowercase

#generate random strings of length 10
names = [''.join(random.choice(letters) for i in range(10)) for x in range(10000)]

# let db contain 20 of these words plus some single character strings
db = [random.choice(names) for x in range(20)] + ["a", "b", "c", "d", "e"]
random.shuffle(db)

%timeit func1(names, db)
%timeit func1_np(names, db)

# numpy is more than twice as fast

12.2 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.55 ms ± 109 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Problem 2

In [112]:
def search_pairs(coordinates, r0):
    # calc distance matrix: pair_dist[i,j] is distance between ith and jth point
    pair_dists = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates, axis=2)
    # check which of the points are in the circle with radisu r0
    points_in_r0 = np.linalg.norm(coordinates, axis = 1) < r0
    
    # and create a logical matrix points_in_r0' ^ points_in_r0
    mask_r0 = points_in_r0[:, np.newaxis] ^ points_in_r0
    # create another logical matrix that is true below the diagonal
    mask_uniq_dists = np.tril(np.ones_like(mask_r0), k=-1)
    
    # select the unique distance values that are in the circle using the above two logical matrices
    uniq_dists = pair_dists[mask_r0 & mask_uniq_dists]
    # select the three laregst such values
    three_largest = np.partition(uniq_dists, -3)[-3:]
    
    # return the indexes of these points that that are largest
    return np.argwhere(mask_r0 & mask_uniq_dists & np.isin(pair_dists, three_largest))

In [113]:
coordinates = np.array(
    [[0.968, 0.313],
     [0.692, 0.876],
     [0.895, 0.085],
     [0.039, 0.17 ],
     [0.878, 0.098]]
    )
circle_r0 = 0.9

print(search_pairs(coordinates, circle_r0))



[[2 1]
 [3 0]
 [3 1]]


In [118]:
coordinates = np.random.rand(10000, 2)

print(search_pairs(coordinates, 0.3))

[[5862 1936]
 [6060 5862]
 [6144 5862]]
